### ISSUE TITLE
"TypeError: Can't convert 'ConnectionError' object to str implicitly" on requests errors

### ISSUE THREAD

**Issue by matslindh** [imbo/imboclient-python#9]
When an operation fails in requests, the library fails (in the python 3 version, at least) to raise the proper exception because of a concatenation issue.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "load_crossad.py", line 34, in <module>
    main()
  File "load_crossad.py", line 28, in main
    crossad.import_ads(date, publication)
  File "/opt/ddb/adpresenter/adpresenter/adpresenter/importers/base.py", line 50, in import_ads
    meta['imbo_id'] = utils.convert_pdf_and_upload_to_imbo(self.imbo_client, path)
  File "/opt/ddb/adpresenter/adpresenter/adpresenter/utils.py", line 89, in convert_pdf_and_upload_to_imbo
    response = client.add_image(output)
  File "/opt/ddb/adpresenter/lib/python3.4/site-packages/imboclient/client.py", line 48, in add_image
    return self._wrap_result_json(http_add_image, [200, 201], 'Could not add image.')
  File "/opt/ddb/adpresenter/lib/python3.4/site-packages/imboclient/client.py", line 246, in _wrap_result_json
    response = self._wrap_result(function, success_status_codes, error)
  File "/opt/ddb/adpresenter/lib/python3.4/site-packages/imboclient/client.py", line 257, in _wrap_result
    raise self.ImboTransportError(error + ', HTTP library returned error: ' + request_error)
TypeError: Can't convert 'ConnectionError' object to str implicitly
```

**Comment by andreasrs** [comment]
https://github.com/imbo/imboclient-python/pull/10

**Comment by andreasrs** [comment]
PR merged. Closing.
